### ISSUE TITLE
Visual adjustments to Target Management

### ISSUE THREAD

**Issue by rcruz** [blackberry/webworks-gui#127]
Some minor adjustments to make sure our UI is clear and consistent.
- Border on the navigation area for Target Management:
  - .title-menu-item needs 1px border with color #333333  
- Font color of targets in the list
  - #565E66
- Order of the icons on a target item
  - Config icon first, Trash can on the right most side
- Background color on hover of the config icon
  - #CCCCCC

**Comment by rcruz** [comment]
@kflores772

**Comment by kflores772** [comment]
@rcruz the changes can be seen in the image below. 

I only added a border-bottom to the title-item-menu since, with a full border, the border between Certificates and the Target Management navigation buttons would look thicker than the rest.

One thing to note is that the config target button does not have a separate image for when it is hovered. You may notice a difference when comparing the look of the hover between this button and the delete target button.

![screen shot 2014-04-02 at 11 16 54 am](https://cloud.githubusercontent.com/assets/4356727/2592896/197c7ab2-ba7a-11e3-99a4-f605abadeeec.png)
